---
# tasks file for dbservers

- name: Ensure mysql-server is installed
  yum: name=mysql-server state=present
  when: ansible_os_family == "RedHat"
  
- name: Ensure mysql-server is installed
  apt: name=mysql-server state=present
  when: ansible_os_family == "Debian"
   
- name: Ensure mysqld is running
  service: name=mysqld state=started
  when: ansible_os_family == "RedHat"

- name: Ensure mysql is running
  service: name=mysql state=started
  when: ansible_os_family == "Debian"
  notify: Restart mysql-server

  

 